INSERT INTO CALENDAR_EVENT VALUES (1,CURRENT_DATE,'TestHeader', 'TestBody')
INSERT INTO CALENDAR_EVENT VALUES (2,CURRENT_DATE,'TestHeader', 'TestBody')
INSERT INTO CALENDAR_EVENT VALUES (3,CURRENT_DATE,'TestHeader', 'TestBody')